# Generated by Django 3.1.1 on 2020-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200928_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tags', models.ManyToManyField(to='blog.TaggedPost')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ManyToManyField(to='blog.Collection'),
        ),
    ]
