# Generated by Django 3.1.1 on 2020-09-28 14:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0008_auto_20200928_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedpost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='TaggedPost',
        ),
    ]
