# Generated by Django 3.1.1 on 2020-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
